### ISSUE TITLE
Can't open GridcoinResearch-QT Raspberry Pi

### ISSUE THREAD

**Issue by IronFixXxeR** [Steffov/GRC-Scripts#3]
I'm running Raspbian OS 4.4.50-v7+ (Debian Jessie with Pixel).

The installation of your script went smoothly.  I installed the -qt shortcut in the "Office" menu.  When I try to open this shortcut or even the application in /usr/share/applications I get an error windows that says:

`Invalid desktop entry file: '/usr/share/applications/gridcoinresearch-qt.desktop'`

I did move my rootfs from the 16GB microSD card to my larger 64GB USB drive.  Not sure if this has anything to do with it.

I'm still learning my way around Linux so I may need a little extra help in trying to solve this.  Thanks!

**Comment by Steffov** [comment]
Thanks for reporting this!
Could you please post the content of one of your another .desktop files in the `/usr/share/applications/` folder? Perhaps the Raspbian OS handle the menu entries in a different way?! With an example from an original entry we can compare.

Thanks!

**Comment by IronFixXxeR** [comment]
Sorry for spam.

[Desktop Entry]
Version=1.0
Terminal=false
Icon=libreoffice-base
Type=Application
Categories=Office;Database;
Exec=libreoffice --base %U
MimeType=application/vnd.oasis.opendocument.database;application/vnd.sun.xml.base;
Name=LibreOffice Base
GenericName=Database Development
GenericName[ug]=ساندان ئىجادىيىتى
GenericName[bn]=ডাটাবেস ডেভেলপমেন্ট
GenericName[st]=Database Development
GenericName[sk]=Vývoj databáz
GenericName[pa_IN]=ਡਾਟਾਬੇਸ ਡਿਵੈਲਮੈਂਟ
GenericName[xh]=Database Development
GenericName[be]=База даных
GenericName[pl]=Opracowanie i rozwój bazy danych
GenericName[uz]=Maʼlumot bazasi
GenericName[kk]=Дерекқор
GenericName[eo]=Datumbaza evoluigo
GenericName[bg]=Разработване на бази от данни
GenericName[pt]=Desenvolvimento da base de dados
GenericName[ast]=Desendolcu de bases de datos
GenericName[sl]=Razvoj zbirk podatkov
GenericName[km]=ការ​អភិវឌ្ឍន៍​មូលដ្ឋាន​ទិន្នន័យ
GenericName[hi]=डेटाबेस विकास
GenericName[en_GB]=Database Development
GenericName[en]=Database Development
GenericName[gd]=Leasachadh stòir-dhàta
GenericName[mr]=कोष विकास
GenericName[ga]=Forbairt Bunachar Sonraí
GenericName[fi]=Tietokantakehitys
GenericName[cy]=Datblygu Cronfa Ddata
GenericName[de]=Datenbankentwicklung
GenericName[ta]=தரவுத்தள உருவாக்கம்
GenericName[mk]=Развој на база на податоци
GenericName[id]=Pengembangan Basis Data
GenericName[eu]=Datu-baseen garapena
GenericName[ar]=تطوير قواعد البيانات
GenericName[da]=Databaseudvikling
GenericName[cs]=Vývoj databáze
GenericName[hr]=Razvoj baze podataka
GenericName[te]=డాటాబేస్ డెవలప్‌మెంట్
GenericName[ne]=डेटाबेस विकास
GenericName[ja]=データベース開発
GenericName[nr]=Database Development
GenericName[tr]=Veritabanı Geliştirme
GenericName[et]=Andmebaasihaldus
GenericName[zh_CN]=数据库开发
GenericName[ka]=Database Development
GenericName[si]=දත්තසමුදාය සංවර්ධනය
GenericName[hu]=Adatbázis-fejlesztés
GenericName[fa]=تولید پایگاه داده
GenericName[en_ZA]=Database Development
GenericName[fr]=Développement de base de données
GenericName[tn]=Database Development
GenericName[om]=Uuminsa Kuusaa Deetaa
GenericName[or]=ତଥ୍ୟାଧାର ବିକାଶ
GenericName[uk]=База даних
GenericName[ca_valencia]=Desenvolupament de bases de dades
GenericName[gu]=ડેટાબેઝ ડેવલોપમેન્ટ
GenericName[ml]=ഡേറ്റാബെയിസ് ഡവലപ്മെന്റ്
GenericName[mn]=Өгөгдлийн сангийн хөгжүүлэлт
GenericName[th]=Database Development
GenericName[ve]=Database Development
GenericName[ko]=데이터베이스 개발
GenericName[br]=Diorren ar stlennvon
GenericName[ts]=Database Development
GenericName[pt_BR]=Desenvolvimento de banco de dados
GenericName[he]=פיתוח מסדי נתונים
GenericName[ca]=Desenvolupament de bases de dades
GenericName[el]=Ανάπτυξη βάσεων δεδομένων
GenericName[nb]=Databaseutvikling
GenericName[nso]=Tšwetšopele ya dathapeisi
GenericName[bs]=Razvoj baza podataka
GenericName[nn]=Databaseutvikling
GenericName[ss]=Database Development
GenericName[ru]=База данных
GenericName[zh_TW]=資料庫開發
GenericName[is]=Hönnun gagnagrunna
GenericName[af]=Databasisontwikkeling
GenericName[dz]=Database Development
GenericName[oc]=Desvolopament de banca de donadas
GenericName[es]=Desarrollo de bases de datos
GenericName[nl]=Databaseontwikkeling
GenericName[zu]=Database Development
GenericName[as]=ডাটাবেইচ বিকাশ
GenericName[lv]=Datubāžu izstrāde
GenericName[tg]=Database Development
GenericName[gl]=Desenvolvemento de bases de datos
GenericName[rw]=Gukora ububikoshingiro
GenericName[vi]=Phát triển cơ sở dữ liệu
GenericName[kmr_Latn]=Pêşdebirê Danegeh
GenericName[sr]=Развој база података
GenericName[ro]=Dezvoltare de baze de date
GenericName[it]=Sviluppo di database
GenericName[sv]=Databasutveckling
GenericName[lt]=Duomenų bazės kūrimas
Comment=Manage databases, create queries and reports to track and manage your information by using Base.
Comment[he]=ניהול מסדי נתונים, יצירת שאילתות ודוחות כדי לעקוב ולנהל את המידע שלך באמצעות תוכנת מסד הנתונים.
Comment[ko]=Base를 사용하여 데이터베이스를 관리하고, 추적할 쿼리와 보고서를 만들며, 정보를 관리합니다.
Comment[be]=Кіруйце базамі даных, стварайце звароты і справаздачы, каб зважаць на, і кіраваць інфармацыяй з дапамогаю Base.
Comment[lt]=Duomenų bazių programa galima tvarkyti duomenų bazes, rašyti užklausas ir ataskaitas.
Comment[ve]=Langani dzidatabase, vhumbani dzimbudziso na mivhigo u itela u londa na u langa vhuṱanzi haṅu nga u shumisa Base.
Comment[km]=គ្រប់គ្រង​មូលដ្ឋាន​ទិន្នន័យ បង្កើត​សំណួរ និង​របាយការណ៍ ដើម្បី​តាមដាន និង​ចាត់ចែង​ព័ត៌មាន​ដោយ​ប្រើ Base ។
Comment[pl]=Administruj bazami danych, twórz kwerendy i raporty aby efektywnie zarządzać informacją używając programu Base.
Comment[pa_IN]=ਬੇਸ (Base) ਨਾਲ ਆਪਣਾ ਡਾਟਾਬੇਸ ਸੰਭਾਲੋ, ਸਵਾਲ ਬਣਾਓ ਅਤੇ ਨਿੱਜੀ ਜਾਣਕਾਰੀ ਨੂੰ ਜਾਂਚਿਆ ਅਤੇ ਪ੍ਰਬੰਧ ਕੀਤਾ ਜਾ ਸਕਦਾ ਹੈ।
Comment[tn]=Manage databases, create queries and reports to track and manage your information by using Base.
Comment[gl]=Xestionar bases de datos, crear consultas e informes para rastrexar e xestionar a súa información usando Base.
Comment[it]=Usando Base puoi gestire i database e creare ricerche e rapporti per controllare e organizzare le tue informazioni.
Comment[mr]=Base चा वापर करून कोष व्यवस्थापीत करा, तसेच माहिती नियंत्रण व व्यवस्थापन करीता चौकशी व अहवाल बनवा.
Comment[bg]=С Base можете да управлявате бази от данни и да създавате заявки и справки, за да следите и управлявате Вашата информация.
Comment[nso]=Laola didathapeisi, hlama dipotšišo le dipego bakeng sa go latedišiša le go laola tshedimošo ya gago o diriša Base.
Comment[mn]=Base танд өгөгдлийн сангууд зохицуулах, асуулга болон тайлан үүсгэх боломж олгоно.
Comment[gu]=બેઝ વડે ડેટાબેઝોનું વ્યવસ્થાપન, પ્રશ્ર્નો બનાવવા અને અહેવાલોનું ઘ્યાન અને માહિતીનું વ્યવસ્થાપન કરવામાં આવે છે.
Comment[as]=Base ব্যৱহাৰ কৰি ডাটাবেইচবোৰ পৰিচালনা কৰক, ট্ৰেক আৰু পৰিচালনা কৰিবলৈ প্ৰশ্ন আৰু সংবাদবোৰ সৃষ্টি কৰক।
Comment[ro]=Gestionați baze de date, creați interogări și rapoarte pentru a urmări și gestiona informațiile dumneavoastră folosind Base.
Comment[si]=Base භාවිතා කරමින් දත්ත ගබඩා පාලනය කරන්න, ඔබගේ තොරතුරු හඹා යාමට සහ පාලනය කරීමට විමසුම් සහ වාර්තා සාදන්න.
Comment[or]= ଆଧାର ଉପୟୋଗ କରି ତଥ୍ଯ ସଞ୍ଚଯଗୁଡିକ ପରିଚାଳନା ,ପ୍ରଶ୍ନଗୁଡିକୁ ସୃଷ୍ଟି ଏବଂ ରିପୋର୍ଟଗୁଡିକୁ ଚିହ୍ନଟ କର ଏବଂ   ତୁମ ସୂଚନାକୁ ପରିଚାଳନା କର।
Comment[cs]=Base umožňuje vytvářet a spravovat databáze a vytvářet dotazy a sestavy pro sledování a správu vašich informací.
Comment[nl]=Met Base kunt u databases beheren, query's en rapporten maken om uw gegevens te controleren en beheren.
Comment[en_ZA]=Manage databases, create queries and reports to track and manage your information by using Base.
Comment[vi]=Quản lý cơ sở dữ liệu, tạo truy vấn và báo cáo để theo dõi và quản lý thông tin bằng Base.
Comment[ss]=Phatsa idathabhesi, yakha sibuti bese uyabuta imibiko yekulandzelela nekuphatsa lwati lwakho ngekusebentisa Base.
Comment[ne]=बेसको प्रयोगद्वारा डाटाबेसहरू प्रबन्ध गर्नुहोस्, ट्रयाकमा क्वेरीहरू र प्रतिवेदन सिर्जना गर्नुहोस् र तपाईंको सूचना प्रबन्ध गर्नुहोस् ।
Comment[da]=Administrer databaser, opret forespørgsler og rapporter til at spore og administrere dine informationer ved at bruge Base.
Comment[cy]=Rheoli cronfeydd data, creu ymholiadau ac adroddiadau i ddilyn a rheoli eich gwybodaeth drwy ddefnyddio Base.
Comment[es]=Gestione bases de datos, cree consultas e informes para controlar y editar información con Base.
Comment[et]=Base võimaldab kasutada andmebaase ja luua andmete jälgimiseks ning haldamiseks päringuid ja aruandeid.
Comment[fr]=Base - Gestion de bases de données, création de requêtes et rapports.
Comment[zh_TW]=使用 Base 來管理資料庫、建立查詢與報告，以追蹤及管理您的資訊。
Comment[zh_CN]=使用 Base 管理数据库并创建查询和报表，以对信息进行跟踪和管理。
Comment[om]=Base fayyadamuun kuusaa deetaa taligi, gaafataa fi gabaasota odeeffannoo kee hordofuu fi taliguuf oolan uumi.
Comment[pt_BR]=Gerencie bancos de dados, crie consultas e relatórios para rastrear e gerenciar suas informações por meio do Base.
Comment[gd]=Rianaich stòir-dhàta, cruthaich iarrtasan is aithisgean gus am fiosrachadh agad a lorgadh agus a rianachd le Base.
Comment[ast]=Alministrar bases de datos, crear consultes ya informes pa siguir y alministrar información emplegando Base.
Comment[uz]=Base rdamida hisobotlar, maʼlumotar bazasini boshqarish.
Comment[te]=దత్తంశస్థానముల నిర్వాహణ,ప్రశ్నలు మరియు నివేదనలు మరియు స్థానము తో ఉపయోగించిన మీ సమాచారమును నిర్మించు.
Comment[ca]=Gestioneu bases de dades i creeu consultes i informes per fer el seguiment i gestionar informació amb el Base.
Comment[sv]=Hantera databaser, skapa sökningar och rapporter för att spåra och hantera information med hjälp av Base.
Comment[kk]=Base көмегімен дерекқорды басқару және ақпараттарыңызды қадағалау және басқару үшін сұранымдар мен есептемелерді жасауға болады.
Comment[ml]=അടിസ്ഥാനമുപയോഗിച്ച്  ഡേറ്റാബേസ് കൈകാര്യം ചെയ്യുകയും ചോദ്യം സൃഷ്ടിക്കുകയും ട്രാക്കില് റിപ്പോര്ട്ട് ചെയ്യുകയും താങ്കളുടെ വിവരങ്ങള്  കൈകാര്യം ചെയ്യുകയും ചെയ്യാം.
Comment[bs]=Upravljanje bazama podataka, kreiranje upita i izvještaja radi praćenja i upravljanja vašim informacijama koristeći Base.
Comment[ca_valencia]=Gestioneu bases de dades i creeu consultes i informes per fer el seguiment i gestionar informació amb el Base.
Comment[mk]=Уредувајте бази на податоци, креирајте барања и извештаи за следење и управување на вашите информации со користење на Base.
Comment[de]=Verwalten von Datenbanken, Erstellen von Abfragen und Berichten - Base macht's möglich.
Comment[el]=Διαχείριση βάσεων δεδομένων, δημιουργία ερωτημάτων και αναφορών και διαχείριση πληροφοριών με τη χρήση της Base.
Comment[ga]=Bainistigh bunachair shonraí, cruthaigh iarratais agus tuairiscí chun do chuid faisnéise a láimhseáil le Base.
Comment[sk]=Spravujte databázy a vytvárajte dotazy a zostavy na správu a analýzu svojich informácií s použitím Base.
Comment[ta]=தரவுத்தளங்களை மேலாளவும், வினவல்கள் அறிக்கைகள் கொண்டு உங்கள் தகவலை மேலாளவும் பேஸைப் பயன்படுத்து.
Comment[uk]=Керування базами даних, створення запитів та звітів для стеження та керування вашою інформацією.
Comment[en_GB]=Manage databases, create queries and reports to track and manage your information using Base.
Comment[zu]=Lawula idatabheyzi, yenza amakhwiri nemibiko ukuze uthole futhi ulawule ukwaziswa kwakho ngokusebenzisa iBheysi.
Comment[fi]=Hallinnoi tietokantoja, luo kyselyjä ja seurantaraportteja, ja hallinnoi tietojasi käyttämällä Base -ohjelmaa.
Comment[nr]=Phatha amabulungelo wekhompyutha, enza imibuzo nemibiko nokulandela nokuphatha ilwazi lakho ngokusebenzisa iBulungelo lekhompyutha.
Comment[ja]=Base を使用することで、データベースを管理し、クエリーとレポートを作成して、情報を追跡および管理します。
Comment[lv]=Pārvaldiet datubāzes, veidojiet vaicājumus un atskaites, lai izsekot un vadītu informāciju, lietojot Base.
Comment[pt]=Gestão de bases de dados, criar consultas e relatórios para controlar e gerir as informações através do Base.
Comment[ru]=Управление базами данных, создание запросов и отчётов для слежения и управления вашей информацией при помощи Base.
Comment[tr]=Base kullanarak veritabanlarını yönetebilir, sorgular ve raporlar oluşturarak bilgilerinizi takip edebilirsiniz.
Comment[xh]=Lawula iziseko zeenkcukacha, dala iintandabuzo neengxelo ukuze ulande ekhondweni ngokunjalo ulawule ulwazi lwakho ngokusebenzisa u-Base.
Comment[sl]=S programom Base upravljajte z zbirkami podatkov, ustvarjajte poizvedbe in poročila za sledenje in upravljanje s podatki.
Comment[dz]=གཞི་རྟན་ལག་ལེན་འཐབ་ཐོག་ལས་ གནས་སྡུད་གཞི་རྟན་ཚུ་འཛིན་སྐྱོང་འབད་ནི་དང་ དྲི་དཔྱད་ཚུ་བཟོ་ནི་ རྗེས་ལམ་ལུ་སྙན་ཞུ་འབད་ནི་ རང་དོན་བརྡ་དོན་འཛིན་སྐྱོང་འབད་ནི།
Comment[sr]=Управљајте базама података, направите упите и извештаје за праћење података у програму База.
Comment[th]=จัดการฐานข้อมูล สร้างข้อคำถามและรายงานไปยังแทร็ก และจัดการข้อมูลของคุณโดยการใช้ Base
Comment[bn]=বেস ব্যবহার করে আপনার তথ্য অনুসরণ এবং ব্যবস্থাপনা করতে, ডাটাবেস ব্যবস্থাপনা, কোয়েরি এবং প্রতিবেদন তৈরি করুন।
Comment[fa]=با استفاده از دادگان، پایگاه‌داده‌ها را اداره کنید و برای ردیابی و مدیریت اطلاعاتتان پرس و جو و گزارش ایجاد کنید.
Comment[br]=Base - Ardeiñ stlennvonoù, krouiñ azgoulennoù ha danevelloù
Comment[id]=Mengelola basis data, membuat kuiri, dan laporan untuk melacak dan mengelola informasi menggunakan Base.
Comment[kmr_Latn]=Danegehan bi rê ve bibe, jêpirsînan bike, raporan bişopîne û zanîna xwe ya Base bikar bîne.
Comment[nn]=Med Base kan du handtera databasar, laga spørjingar og rapportar for sporing og handtering av informasjon.
Comment[st]=Laola didatapeisi, bopa ditletlebo le ditlaleho bakeng sa ho latedisisa le ho laola tlhahisoleseding ya hao ka ho sebedisa Base.
Comment[tg]=Идоракунии МД, сохтани дархостҳо ва ҳисобот, идоракунии маълумот таввасути Base сурат мегиранд.
Comment[ug]=سانداننى باشقۇرۇش، سۈرۈشتۈرۈش ۋە دوكلات قۇرۇش شۇنداقلا ئۇچۇرنى ئىز قوغلاش ۋە باشقۇرۇش ئېلىپ بېرىشتا Base ئىشلىتىدۇ.
Comment[af]=Bestuur databasisse, skep navrae en verslae om u inligting na te speur en te bestuur, met Base.
Comment[oc]=Base - Gestion de bancas de donadas, creacion de requèstas e rapòrts.
Comment[ar]=إدارة قواعد البيانات، وإنشاء الاستعلامات والتقارير وتتبّع وإدارة معلومات باستخدام بيز.
Comment[rw]=Kuyobora ububikoshingiro, kurema ibibazo na raporo kugira ngo ugenzure kandi uyobore ibyatanzwe byawe ukoresheje Base.
Comment[is]=Meðhöndla gagnagrunna, búa til fyrirspurnir og skýrslur til að hafa stjórn á upplýsingaflæði með Base.
Comment[en]=Manage databases, create queries and reports to track and manage your information by using Base.
Comment[ts]=Tirhisa swihlayisela-rungula, endla mindzavisiso ni swiviko leswaku u landzelerisisa rungula ra wena hi ku tirhisa Base.
Comment[nb]=Håndter databaser, lag spørringer og rapporter og håndter informasjon ved hjelp av Base.
Comment[hr]=Upravlja bazama, stvara upite i izvještaje za praćenje, te upravlja vašim informacijama.
Comment[eu]=Datu-baseak kudeatu eta kontsultak eta txostenak sortu Base erabiliz informazioaren segimendua egiteko eta hura kudeatzeko.
Comment[hi]=बेस के प्रयोग से डेटाबेस प्रबंधित करता है, प्रश्न बनाता है, ट्रैक रिपोर्ट करता है आपकी सूचना की देखभाल करता है.
Comment[eo]=Administri datumbazojn, krei informpetojn kaj raportojn por kontroli kaj administri viajn informojn per Datumbazo.
Comment[hu]=Adatbázisok kezelése, lekérdezések és jelentések készítése a Base használatával.
Comment[ka]=მართავს მონაცემთა ბაზებს, ქმნის მოთხოვნებს და მოხსენებებს რათა ჩაიწეროს და მართოს თქვენი ინფორმაცია  Base-ის გამოყენებით.
StartupNotify=true
X-GIO-NoFuse=true
Keywords=Data;SQL;
InitialPreference=5
StartupWMClass=libreoffice-base
X-KDE-Protocols=file,http,smb,ftp,webdav

Actions=NewDocument;
[Desktop Action NewDocument]
Name=New Database
Exec=libreoffice --base

**Comment by Steffov** [comment]
Hmm. Looks very similar to my one.
When you open `/usr/share/applications/gridcoinresearch-qt.desktop` do you see this?
"[Desktop Entry]
Encoding=UTF-8
Name=GridcoinResearch-Qt
Comment=Gridcoin P2P Cryptocurrency
Exec=/usr/bin/gridcoinresearch %u
Terminal=false
Type=Application
Icon=grc-small
MimeType=x-scheme-handler/gridcoin;
Categories=Application;Office;"

If yes...
1. Please typ `gridcoinresearch` from anywhere into your consol and see if the wallet is starting. Please post the error output here.
2. Please check if "gridcoinresearch-qt.desktop" has the same rights as the other .desktops files in `/usr/share/applications/`. Easiest way... `ls -al /usr/share/applications/`

**Comment by IronFixXxeR** [comment]
When I look into the gridcoinresearch-qt.desktop file there is nothing.  I copied your info into the file and saved it.  Same error as before when trying to start it.

1. When typing `gridcoinresearch` into console I get this:

`pi@raspberrypi:~ $ gridcoinresearch`

`-bash: gridcoinresearch: command not found`

2. When checking the rights of the .desktop files it shows

`-rw-r--r--   1 root root   240 May  6 21:10 gridcoinresearch-qt`

and

`-rw-r--r--   1 pi   pi     240 May  6 05:50 gridcoinresearch-qt.desktop`

I did install the dameon and the -qt just to see if that would solve the issue.

**Comment by Scalextrix** [comment]
If you want to start gridcoin from the command line, try typing `gridcoinresearch-qt`, I cant test it from here as I onlyuse the daemon but it may work for you

**Comment by Steffov** [comment]
@IronFixXxeR sorry for the delay but I had less time in the last days.
It seems that `sudo install -m 755 gridcoinresearch /usr/bin/gridcoinresearch` from my script doesn't worked in your case. That could be the reason for your error message: command not found. 

Please check:
Go into the folder ~/Gridcoin-Research and try the command `gridcoinresearch`(that's the command to start the qt wallet) again. If this command is working and the wallet is starting it's for sure that `sudo install -m 755 gridcoinresearch /usr/bin/gridcoinresearch` did not worked during the install process of my script! If this is the case please stay in ~/Gridcoin-Research and enter the command `sudo install -m 755 gridcoinresearch /usr/bin/gridcoinresearch. Please give me the output of this command.

BTW: You don't need the daemon for the qt wallet. ;)

**Comment by IronFixXxeR** [comment]
Here is what I tried.

`pi@raspberrypi:~ $ gridcoinresearch-qt`

`bash: gridcoinresearch-qt: command not found`

`pi@raspberrypi:~ $ cd /home/pi/Gridcoin-Research`

`pi@raspberrypi:~/Gridcoin-Research $ gridcoinresearch`

`bash: gridcoinresearch: command not found`

`pi@raspberrypi:~/Gridcoin-Research $ sudo install -m 755 gridcoinresearch /usr/bin/gridcoinresearch`

`install: cannot stat ‘gridcoinresearch’: No such file or directory`

**Comment by Steffov** [comment]
I updated my script in this moment. Please download the new gridly version (1.0.2) or do a `git pull` if you cloned my repository.

Okay. The built process was definitely __not__ successful! If it was successful it would be the `gridcoinresearch` in `~/Gridcoin-Research`. So, please start from scratch, delete `~/Gridcoin-Research` and run the new version of gridly for the installation of the qt wallet.

Please keep an extra eye on the built process (step 3). This should take quite a long time and you should see a lot of code lines on the screen (incl. warnings).

After the installation check the `~/Gridcoin-Research` folder for the `gridcoinresearch` file.

**Comment by Steffov** [comment]
Okay I had some time and set up a Debian 8.0 test environment for debugging purpose. I updated gridly now to 1.0.3. with slight changes in installed / needed compiling tools for qt. So please be that kind and download the latest gridly version again and delete ~/Gridcoin-Research too . In additional check out if your Linux user is attached to the sudo group! If **not** do...
`su [password] ` 
`gpasswd -a [user] sudo`
__This is very important otherwise gridly is not able to install the needed compiling tools.__

With the latest version (1.0.3) everything runs fine on my test environment. Good luck!

**Comment by IronFixXxeR** [comment]
I ran the new script (1.0.3) after deleting my `~/Gridcoin-Research` directory.  It skipped through step 3 very fast (1 second or so) when I selected qt.

There are many more files in the directory now but still no `gridcoinresearch`

`pi@raspberrypi:~ $ cd /home/pi/Gridcoin-Research`
`pi@raspberrypi:~/Gridcoin-Research $ ls`
`CHANGELOG.md                  contrib  doc                   INSTALL  Makefile.Debug  `  `object_script.gridcoinresearch.Debug    object_script.gridcoinstake.Debug    README     share`
`CompilingGridcoinOnLinux.txt  COPYING  gridcoinresearch.pro  libs     Makefile.Release`  `object_script.gridcoinresearch.Release  object_script.gridcoinstake.Release  README.md  src`

**Comment by IronFixXxeR** [comment]
I added my user which is Pi to the sudo user group with this:

`pi@raspberrypi:~ $ sudo gpasswd -a pi sudo`
`Adding user pi to group sudo`

I have restarted the Pi after doing this step.

Here are the files in my ~/Gridcoin-Research now.  More than before but still missing the `gridcoinresearch` one.

`pi@raspberrypi:~ $ cd /home/pi/Gridcoin-Research`
`pi@raspberrypi:~/Gridcoin-Research $ ls`
`CHANGELOG.md                  doc                   Makefile.Debug `                         `object_script.gridcoinstake.Debug    share`
`CompilingGridcoinOnLinux.txt  gridcoinresearch.pro  Makefile.Release`                        `object_script.gridcoinstake.Release  src`
`contrib                       INSTALL               object_script.gridcoinresearch.Debug    README`
`COPYING                       libs                  object_script.gridcoinresearch.Release  README.md`

Step 3 went by very fast (1 second or so).  I could not see the messages displayed as it went to step 4 right afterwards.  Not able to start the wallet.

**Comment by Steffov** [comment]
Are you sure that pi is now in the group sudo? I'm wondering because `sudo gpasswd -a pi sudo` can only work if pi was in the group before. ;)
That's the reason why I'm actually said use this:
`su [password]`
`gpasswd -a [user] sudo`

If pi is really in the sudo group it still looks like the tools which are needed for compiling are still not installed! We can trigger this issue only down by doing it step by step and by hand. :(
If you like to debug, please enter this into your console...
`sudo apt-get install ntp git build-essential libssl-dev libdb-dev libdb++-dev libqrencode-dev libcurl4-openssl-dev curl libzip-dev libzip2 libboost-atomic-dev libboost-chrono-dev libboost-date-time-dev libboost-filesystem-dev libboost-program-options-dev libboost-serialization-dev libboost-system-dev libboost-thread-dev libboost-all-dev`
... and post the output.

**Comment by IronFixXxeR** [comment]
I'm not sure that works.

When I type `su [password]` I get `No passwd entry for user '*****'`

**Comment by Steffov** [comment]
Only to avoid mistakes...
`su <enter>`
`[your su password] <enter>`
`gpasswd -a [your pi user] sudo <enter>`
`exit <enter>`

And still what is your output of:
`sudo apt-get install ntp git build-essential libssl-dev libdb-dev libdb++-dev libqrencode-dev libcurl4-openssl-dev curl libzip-dev libzip2 libboost-atomic-dev libboost-chrono-dev libboost-date-time-dev libboost-filesystem-dev libboost-program-options-dev libboost-serialization-dev libboost-system-dev libboost-thread-dev libboost-all-dev`

**Comment by IronFixXxeR** [comment]
Ok.  I setup the su password for my pi user.  Ran the installer again and same error.

I ran the other command and got this

`Reading package lists... Done`
`Building dependency tree`       
`Reading state information... Done`
`build-essential is already the newest version.`
`curl is already the newest version.`
`git is already the newest version.`
`libboost-all-dev is already the newest version.`
`libboost-atomic-dev is already the newest version.`
`libboost-chrono-dev is already the newest version.`
`libboost-date-time-dev is already the newest version.`
`libboost-filesystem-dev is already the newest version.`
`libboost-program-options-dev is already the newest version.`
`libboost-serialization-dev is already the newest version.`
`libboost-system-dev is already the newest version.`
`libboost-thread-dev is already the newest version.`
`libcurl4-openssl-dev is already the newest version.`
`libdb++-dev is already the newest version.`
`libdb-dev is already the newest version.`
`libqrencode-dev is already the newest version.`
`libssl-dev is already the newest version.`
`libzip-dev is already the newest version.`
`libzip2 is already the newest version.`
`ntp is already the newest version.`
`0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

**Comment by Steffov** [comment]
That's interesting.
It seems all needed tools for compiling Gridcoin are installed. Good news. :)

Please try now this and post the output...
`cd ~/Gridcoin-Research`
`qmake-qt4 gridcoinresearch.pro USE_QRCODE=1 NO_UPGRADE=1`
If this is not working try this....
`qmake gridcoinresearch.pro USE_QRCODE=1 NO_UPGRADE=1`
**_I need the output of both please.
Make sure your are in the folder `/Gridcoin-Research`!_**

**Comment by Steffov** [comment]
**Please ignore my message above!**

Okay. I just started multiple test environments and was able to track down an issue with missing compiling tools! I added some and updated gridly to version 1.0.4. Please download the latest version and:
1. delete folder /Gridcoin-Research
2. start gridly (qt install process)

This time I double checked the new gridly version on two differed and fresh installed Debian 8.0 environments. In both environments I was able to full complete the qt installation without any error. That failed even on my new test machines with version 1.0.3! So the latest version seems to be the HOTFIX for you. ;) Good luck!

**Comment by IronFixXxeR** [comment]
Success!  The hotfix worked!  Step 3 took quite a long time.  It's open and syncing!  Thank you so much!

**Comment by Steffov** [comment]
Fantastic! I appreciate your contribution and your time in this case. Without you I had never got the information that there is something wrong! :)
